<a href="https://colab.research.google.com/github/oramirezperera/Vectors_linear_algebra/blob/main/affine_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We have three processors while resting we have PT = [10,10,10] and a temperature of 35 celcius degrees.
When the first processor is at max capacity PT=[100,10,10] and T = 60.
When the second processor is at max capacity PT=[10,100,10] and T = 75.
When the third processor is at max capacity PT= [10,10,100] and T = 65.
Which is the temperature with the three processors at max capacity, the processors melt at 150 degrees.

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
def experimental_data():
  p_0 = np.array([10,10,10]) # resting
  p_1 = np.array([100,10,10]) # first processor max capacity
  p_2 = np.array([10,100,10])
  p_3 = np.array([10,10,100])

  p = np.array([p_0,p_1,p_2,p_3]) 
  t = np.array([35,60,75,65]) # temperature solution array
  return p, t

In [5]:
def polynomial_system():
  """ using polynomial system to get the answer """
  equation1 = '10*a0+10*a1+10*a2+b=35'
  equation2 = '100*a0+10*a1+10*a2+b=60'
  equation3 = '10*a0+100*a1+10*a2+b=75'
  equation4 = '10*a0+10*a1+100*a3+b=65'

  p = np.array([[10,10,10,1], [100,10,10,1], [10,100,10,1], [10,10,100,1]]) # capacity processors matrix
  t = np.array([35,60,75,65]) # temperature solution array

  solution = np.linalg.solve(p, t) # numpy solution to the system equation

  return solution

In [6]:
def least_square():
  """ using least square method to get the answer """
  p, t = experimental_data()
  vector = np.column_stack([p, np.ones(len(p))])
  coefs = np.linalg.lstsq(vector, t, rcond=-1)[0] #rcond = -1 to use the machine precision as rcond parameter

  return coefs

In [7]:
def linear_regression():
  """ using linear regression with sklearn """
  p, t = experimental_data()

  regression = LinearRegression().fit(p,t)

  return regression.coef_, regression.intercept_

In [8]:
def temperature(p):
  a, b = linear_regression()
  return a@p+b
  

In [9]:
print(f'polynomial system equation solution')
print(polynomial_system())

polynomial system equation solution
[ 0.27777778  0.44444444  0.33333333 24.44444444]


In [10]:
print(f'least square solution')
print(least_square())

least square solution
[ 0.27777778  0.44444444  0.33333333 24.44444444]


In [11]:
print(f'linear regression with sklearn')
print(linear_regression())

linear regression with sklearn
(array([0.27777778, 0.44444444, 0.33333333]), 24.444444444444436)


In [12]:
processor_max_capacity = np.array([100,100,100])

In [13]:
print(f'If we put the max capacity of all three processors we got, {temperature(processor_max_capacity)} celcius degrees ')

If we put the max capacity of all three processors we got, 130.0 celcius degrees 


The temperature with the three processors at max capacity is less than 150, that means we can have the three processors running at max capacity at the same time.