<a href="https://colab.research.google.com/github/oramirezperera/Vectors_linear_algebra/blob/main/vector_addition_rgb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using RGB to use them as vectors.
We know if we can represent Python lists as vectors. But if we use + Python will concatenate the two lists and don't add the vectors.
A solution for this could be the following code.

In [ ]:
red = [255, 0, 0]
black = [0, 0, 0]

In [ ]:
print('if we use + it will concatenate the two lists: ', red + black)

if we use + it will concatenate the two lists:  [255, 0, 0, 0, 0, 0]


In [ ]:
def vector_addition(a, b):
  return [i+j for i,j in zip(a,b)] # zip takes iterables (can be zero or more), aggregates them in a tuple, and return it.

In [ ]:
vector_addition(red, black)

[255, 0, 0]

As we can see, now it's a vector addition. But there are easier ways to do it, we can use numpy to do this.

In [ ]:
import numpy as np

In [ ]:
red = np.array(red)
black = np.array(black)
print(red, black)

[255   0   0] [0 0 0]


In [ ]:
print(type(red))

<class 'numpy.ndarray'>


Now red and black are not lists, they are ndarray or numpy arrays. If we add the two vectors with + we will get a vector addition as expected.

In [ ]:
red_and_black = red + black
print(red_and_black)

[255   0   0]


If we have two vectors a = (1, 2, 3, 4, 5) and b = (-1, -2, -3, -4, 5) and we want to get the vector c = a+b

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([-1,-2,-3,-4,5])
c = a + b
print(c)

[ 0  0  0  0 10]


We have the vector  a = [0,0,255]

What if we  add the vectors green + red + a?

What if we  add the vectors green + red?

What if we  add the vectors black - a? makes sense in RGB?


In [ ]:
green = np.array([0,255,0])
a = np.array([0,0,255]) # RGB a is blue

In [ ]:
print('the addition of the vectors green + red + a is:', red+green+a)

the addition of the vectors green + red + a is: [255 255 255]


Above is the code for white in RGB

In [ ]:
print('green + red will be: ', green + red)

green + red will be:  [255 255   0]


Green + red is yellow and the result of the sum of those vectors is the RGB code for yellow

In [ ]:
print('The result of black - a is: ', black-a)

The result of black - a is:  [   0    0 -255]


The algebraic addition of those vectors is [0,0,-255] but in RGB that doesn't make sense, it's not a color.